.gitignore, build/Dockerfile, dappnode_package.json, docker-compose.yml
Fix the url to the logs
* Update the package to the latest version of hoprd
* Make adjustments to the dockerfile and docker-compose
=> Add new release

build/Dockerfile
=> Update the docker image

build/Dockerfile, dappnode_package.json, docker-compose.yml, setup-wizard.yml
Improve dockerfile:
- Now the env variables like db password and api-token can be changed before they were defined on the code
- The upstream variable is defined and is used
- The wizard lets you change the api-token env var
- The identity flag was update for the athens version
=> Update package to athens

.gitignore, Dockerfile, build_dappnode.sh, dappnode_package.json, docker-compose.yml, releases.json, setup-wizard.yml
WIP https://github.com/hoprnet/hoprnet/issues/3820 for details.
=> Improvements to HOPR DappNode package

dappnode_package.json, docker-compose.yml, releases.json
- version bump to 1.90.26
cc @tropicar
=> Version bump to 1.90.26

dappnode_package.json, docker-compose.yml
=> Bump version to 1.90.40

dappnode_package.json, docker-compose.yml
Update to Valencia hotfix 1.90.69
=> Bump to Valencia 1.90.69

dappnode_package.json, docker-compose.yml, releases.json
This contains the newest patch version of hoprd Riga release.
=> Bump to Riga v1.92.9

dappnode_package.json, docker-compose.yml
Bump to new Release Riga version
=> Version bump to 1.92.12

hoprd-grafana-dashboard.json
Add Prometheus mixer metrics into the Grafana dashboard for `release/bratislava`.
=> Add release/bratislava Prometheus mixer metrics into the Grafana dashboard

Dockerfile, dappnode_package.json, docker-compose.yml, hoprd-grafana-dashboard.json, prometheus-targets.json, releases.json
Also configure heartbeat interval to trigger every 20 seconds instead of 60 seconds.
=> Upgrade hoprd to 1.93.3

dappnode_package.json, docker-compose.yml
=> Upgrade hoprd to 1.93.5

dappnode_package.json, docker-compose.yml
Dappnode update to upstream 1.93.7
=> Bump to version 1.93.7

Dockerfile, dappnode_package.json, docker-compose.yml, setup-wizard.yml
- Updated release versions
- Updated hopr-admin build to use source code repository
- Removed some default environment variables which should be set by the user or use internal defaults
=> Update for providence

README.md, docker-compose.yml
- Also update hoprd to latest Providence rc
=> admin: Use latest version

dappnode_package.json, docker-compose.yml
Also expose dyndns domain as config parameter.
=> Update to rc.5 untagged version

README.md, dappnode_package.json, docker-compose.yml
Updates the package to version 2.0.0-rc.7
=> Update to 2.0.0 rc.7

README.md, dappnode_package.json, docker-compose.yml
Bump hoprd image to 2.0.0-rc.10
=> Bump to 2.0.0-rc.10

dappnode_package.json, docker-compose.yml
=> Update Admin UI to 0.6.10

dappnode_package.json, docker-compose.yml
=> Increase memory limit to 3 GB

prometheus-targets.json
Updates metrics endpoint to v3.
Fixes https://github.com/hoprnet/hoprnet/issues/5944
=> Update metrics endpoint to v3

dappnode_package.json, docker-compose.yml
Version normalization to go with tags.
Allow re-signing of package.
=> Version bump for signing

dappnode_package.json, docker-compose.yml
Updates a release to a pre-2.1 docker compose file
=> Fix release 2.0.8

dappnode_package.json, docker-compose.yml
Bump to 1.0.19 due to signing issues.
=> Bump to 1.0.19

dappnode_package.json, docker-compose.yml, setup-wizard.yml
- adds privileged mode so that the node can create threads
- adds more readable setup wizard explanation
- set minimum length requirements on password
=> Fix startup of node's executor

docker-compose.yml, releases.json, setup-wizard.yml
=> Update to HOPR admin compatible with HOPRd 2.1

setup-wizard.yml
=> Update setup wizard regex to make HOPRD_PROVIDER port optional

hoprd.cfg.yaml, setup-wizard.yml
- added missing configuration file value
- improved HOPRD_PROVIDER regex that supports longer gateway URLs
=> Update configuration values and PROVIDER regex

setup-wizard.yml
=> Fix HOPRD_PROVIDER description label

docker-compose.yml
=> Update hopr-admin and use hoprd rc.4

docker-compose.yml, hopr-admin/Dockerfile
Adding build context to hopr admin to get identified as external
=> Adding build context

dappnode_package.json, hoprd.cfg.yaml
=> Adapt changes to 2.2 version

Dockerfile, docker-compose.yml
Add port ranges for Session support introduced in 2.2
Refs https://github.com/hoprnet/hoprnet/issues/6752
=> Enable Session port ranges

dappnode_package.json
=> Update upstream version in dappnode_package.json

dappnode_package.json, docker-compose.yml, hoprd.cfg.yaml
As in title.
Also change the defaults in config file.
=> Add GnosisVPN session port

hopr-admin/Dockerfile
Updates HOPR Admin version to 2.1.14
=> Update hopr-admin to 2.1.14

hoprd.cfg.yaml
=> strategy: Update hoprd.cfg.yaml to match values to hoprd defaults

justfile, package-lock.json, package.json, setup-wizard.yml, shell.nix
Also improve pattern for RPC endpoint URL to allow the use of URLs with query strings. This is useful since some managed RPC endpoint providers use these kind of URLs.
=> env: Add support for HOPRD_NAT
